collector/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView

from collector import views

from .forms import UserLoginForm

app_name = 'collector'
urlpatterns = [
    path("", views.HomeView.as_view(), name="index"),
    path('login/', LoginView.as_view(
            template_name="collector/login.html",
            authentication_form=UserLoginForm
            ), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),

    path('observation/wizard/', views.ObservationWizard.as_view(), name='observation_wizard'),
    path("observation/wizard/success", views.ObservationSuccessView.as_view(), name="create_observation_success"),
    path("map", views.MapView.as_view(), name="map"),
    path('species-autocomplete/', views.SpeciesAutocompleteView.as_view(), name='species_autocomplete'),
    path('plot-autocomplete/', views.PlotAutocompleteView.as_view(), name='plot_autocomplete'),

    path('profile/observations', views.UserObservationsView.as_view(), name='profile_observations'),
    path('profile/export/observations', views.UserExportObservationsView.as_view(), name='profile_observations_export'),
    path('profile/export/images', views.UserExportImagesView.as_view(), name='profile_observations_export_images'),

]

config/urls.py
from django.urls import include, path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('collector.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collector/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


def user_directory_path(instance, filename):
    return f"user_{instance.user.id}/{filename}"

class Plot(models.Model):
    code = models.CharField(max_length=200)
    source = models.CharField(max_length=20, blank=False, null=False, default="system")

    class Meta:
        verbose_name = _('Plot')
        verbose_name_plural = _('Plots')

    def __str__(self):
        return self.code

class Observation(models.Model):
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    plot = models.ForeignKey(Plot, null=True, on_delete=models.CASCADE)
    create_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True, default=None)
    geo_lat = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True, default=None)
    geo_lng = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True, default=None)
    block = models.CharField(max_length=20, blank=True, null=True, default=None)
    row = models.CharField(max_length=20, blank=True, null=True, default=None)
    fertilization = models.BooleanField(default=False, blank=False, null=False)
    cutting = models.BooleanField(default=False, blank=False, null=False)
    chlorophyl = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=None)
    fungal_disease = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=None)
    eat_marks = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=None)
    soil_moisture = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=None)
    electric_conductivity = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=None)
    temperature = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, default=None)
    notes = models.TextField(blank=True, null=True, default=None)

    class Meta:
        verbose_name = _('Observation')
        verbose_name_plural = _('Observations')
        ordering = ['-create_date']

    def __str__(self):
        return f"{self.user.username}-{self.create_date.strftime('%Y%m%d_%H%M%S')}"


class Species(models.Model):
    name = models.CharField(max_length=200)
    user_generated = models.BooleanField(default=False, blank=False, null=False)

    class Meta:
        verbose_name = _('Species')
        verbose_name_plural = _('Species')
        indexes = [models.Index(fields=['name']),]

    def __str__(self):
        return self.name


class ObservationSpecies(models.Model):
    observation = models.ForeignKey(Observation, null=False, related_name="observationspecies", on_delete=models.CASCADE)
    species = models.ForeignKey(Species, null=True, on_delete=models.CASCADE)
    coverage = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True, default=None)

    class Meta:
        verbose_name = _('ObservationSpecies')
        verbose_name_plural = _('ObservationSpecies')


class PlotProperties(models.Model):
    plot = models.ForeignKey(Plot, null=False, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    value = models.CharField(max_length=200)

    class Meta:
        verbose_name = _('Plot Property')
        verbose_name_plural = _('Plot Properties')

collector/forms/wizard_locphoto.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ObservationLocationPhotoForm(forms.Form):
    observation_image = forms.CharField(required = True,
                                        widget=forms.HiddenInput(),
                                        error_messages={"required": _("Please capture an image")})
    geo_lat = forms.CharField()
    geo_lng = forms.CharField()

collector/forms/wizard_measure.py
from django import forms

from django.utils.translation import gettext_lazy as _

class ObservationMeasurementForm(forms.Form):
    chlorophyl = forms.DecimalField(
        required=False,
        max_digits=4,
        decimal_places=0,
        widget=forms.NumberInput(attrs={'step': '1', 'class': 'form-control'}),
        help_text=_("Enter the chlorophyl value as a whole number (0-9999, no decimals).")
    )
    fungal_disease = forms.DecimalField(
        required=False,
        max_digits=4,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'step': '0.01', 'class': 'form-control'}),
        help_text = _("Enter the fungal disease level with up to two decimal places.")
    )
    eat_marks = forms.DecimalField(
        required=False,
        max_digits=4,
        decimal_places=2,
        widget=forms.NumberInput(attrs={'step': '0.01', 'class': 'form-control'}),
        help_text = _("Enter the eat marks level with up to two decimal places.")
    )
    soil_moisture = forms.DecimalField(
        required=False,
        max_digits=4,
        decimal_places=1,
        widget=forms.NumberInput(attrs={'step': '0.1', 'class': 'form-control'}),
        help_text=_("Enter the soil moisture level with up to one decimal place.")
    )
    electric_conductivity = forms.DecimalField(
        required=False,
        max_digits=4,
        decimal_places=0,
        widget=forms.NumberInput(attrs={'step': '1', 'class': 'form-control'}),
        help_text=_("Enter the electric conductivity value as a whole number (0-9999, no decimals).")
    )
    temperature = forms.DecimalField(
        required=False,
        max_digits=4,
        decimal_places=1,
        widget=forms.NumberInput(attrs={'step': '0.1', 'class': 'form-control'}),
        help_text=_("Enter the temperature level with up to one decimal place.")
    )

collector/forms/wizard_notes.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ObservationNotesForm(forms.Form):
    notes = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 5, "cols": 40, 'class': 'form-control'}),
        label="Additional Notes (optional)",
        max_length=2000,
        required=False,
        help_text=_("Max 2000 characters.")
    )

collector/views.py
import base64

from django.core.files.base import ContentFile
from django.views.generic import TemplateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views import View
from django.urls import reverse_lazy, reverse
from django.utils.timezone import now
from django.http import JsonResponse
from .forms import ObservationLocationPhotoForm, ObservationPlotForm, ObservationMeasurementForm, ObservationSpeciesFormSet
from .models import Observation, Species, ObservationSpecies

class HomeView(TemplateView):
    template_name = 'collector/home.html'

class ObservationLocationPhotoView(LoginRequiredMixin, FormView):
    template_name = 'collector/observation_loc_photo.html'
    form_class = ObservationLocationPhotoForm
    success_url = reverse_lazy('collector:create_observation_success')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['step_number'] = 1
        context['step_count'] = 4
        return context

    def form_valid(self, form):

        # Handle valid form submission here
        observation_image = form.cleaned_data['observation_image']
        geo_lat = form.cleaned_data['geo_lat']
        geo_lng = form.cleaned_data['geo_lng']

        # process image
        header, obs_image_encoded = observation_image.split(",", 1)  # Split the header and the base64 data
        obs_image_decoded_data = base64.b64decode(obs_image_encoded)
        timestamp = now().strftime('%Y%m%d_%H%M%S')  # Format: YYYYMMDD_HHMMSS
        filename = f"{timestamp}_user_{self.request.user.id}.png"

        # Process data as needed (e.g., save to database, send email, etc.)
        observation = Observation()
        observation.user = self.request.user
        observation.geo_lat = geo_lat
        observation.geo_lng = geo_lng
        observation.image.save(filename, ContentFile(obs_image_decoded_data))
        observation.save()

        self.success_url = reverse('collector:create_observation_plot', kwargs={'id': observation.id})
        # Return the response to indicate success
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class ObservationPlotView(LoginRequiredMixin, FormView):
    template_name = 'collector/observation_plot.html'
    form_class = ObservationPlotForm
    success_url = reverse_lazy('collector:create_observation_success')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['step_number'] = 2
        context['step_count'] = 4
        return context

    def form_valid(self, form):

        observation_id = self.kwargs.get('id')
        # Fetch the existing observation
        try:
            observation = Observation.objects.get(id=observation_id, user=self.request.user)
        except Observation.DoesNotExist:
            form.add_error(None, "Observation not found or you don't have permission to modify it.")
            return self.form_invalid(form)

        # Handle valid form submission here
        observation.plot = form.cleaned_data['plot']
        observation.block = form.cleaned_data['block']
        observation.row = form.cleaned_data['row']
        observation.fertilization = form.cleaned_data['fertilization']
        observation.cutting = form.cleaned_data['cutting']
        observation.save()

        self.success_url = reverse('collector:create_observation_measurements', kwargs={'id': observation.id})
        # Return the response to indicate success
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class ObservationMeasurementsView(LoginRequiredMixin, FormView):
    template_name = 'collector/observation_measurements.html'
    form_class = ObservationMeasurementForm
    success_url = reverse_lazy('collector:create_observation_success')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['step_number'] = 3
        context['step_count'] = 4
        return context

    def form_valid(self, form):

        observation_id = self.kwargs.get('id')
        try:
            observation = Observation.objects.get(id=observation_id, user=self.request.user)
        except Observation.DoesNotExist:
            form.add_error(None, "Observation not found or you don't have permission to modify it.")
            return self.form_invalid(form)

        observation.chlorophyl = form.cleaned_data['chlorophyl']
        observation.fungal_disease = form.cleaned_data['fungal_disease']
        observation.eat_marks = form.cleaned_data['eat_marks']
        observation.soil_moisture = form.cleaned_data['soil_moisture']
        observation.electric_conductivity = form.cleaned_data['electric_conductivity']
        observation.temperature = form.cleaned_data['temperature']
        observation.save()

        self.success_url = reverse('collector:create_observation_species', kwargs={'id': observation.id})
        return super().form_valid(form)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class ObservationSpeciesView(LoginRequiredMixin, FormView):
    template_name = 'collector/observation_species.html'
    form_class = ObservationSpeciesFormSet
    success_url = reverse_lazy('collector:create_observation_success')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['step_number'] = 4
        context['step_count'] = 4
        context['formset'] = ObservationSpeciesFormSet()
        return context

    def form_valid(self, formset):

        observation_id = self.kwargs.get('id')
        # Fetch the existing observation
        try:
            observation = Observation.objects.get(id=observation_id, user=self.request.user)
        except Observation.DoesNotExist:
            formset.add_error(None, "Observation not found or you don't have permission to modify it.")
            return self.form_invalid(formset)

        for form in formset:
            if form.is_valid():
                u_species = form.cleaned_data.get('species')
                coverage = form.cleaned_data.get('coverage')

                if u_species:
                    species, created = Species.objects.get_or_create(
                            name=u_species,
                            defaults={"user_generated": True,
                                      "name": u_species}
                        )

                    observation_species = ObservationSpecies()
                    observation_species.observation = observation
                    observation_species.species = species
                    observation_species.coverage = coverage
                    observation_species.save()

        # Return the response to indicate success
        return super().form_valid(formset)

    def form_invalid(self, formset):
        return self.render_to_response(self.get_context_data(formset=formset))


class ObservationSuccessView(TemplateView):
    template_name = 'collector/observation_success.html'


class UserLogoutView(LogoutView):
    next_page = reverse_lazy('collector:index')

class MapView(LoginRequiredMixin, TemplateView):
    template_name = 'collector/map.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['observations'] = Observation.objects.all()
        return context


class SpeciesAutocompleteView(View):
    def get(self, request, *args, **kwargs):
        # Check if query parameter 'q' is present in the GET request
        query = request.GET.get('q', '')

        # If query length is less than 3, return an empty list immediately
        if len(query) < 3:
            return JsonResponse([], safe=False)

        # Filter species names based on the query (case-insensitive search)
        species = Species.objects.filter(name__istartswith=query, user_generated=False).order_by('name')[:25]
        suggestions = [species.name for species in species]

        # Return the matching species names as a JSON response
        return JsonResponse(suggestions, safe=False)

collector/views/autocomplete.py
from django.http import JsonResponse
from django.db.models import Prefetch
from django.views import View

from collector.models import Species, Plot, PlotProperties

class SpeciesAutocompleteView(View):

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q', '')

        if len(query) < 3:
            return JsonResponse([], safe=False)

        species = Species.objects.filter(name__istartswith=query, user_generated=False).order_by('name')[:25]
        suggestions = [species.name for species in species]

        return JsonResponse(suggestions, safe=False)

class PlotAutocompleteView(View):
    def get(self, request, *args, **kwargs):
        query = request.GET.get('q', '')

        if len(query) < 2:
            return JsonResponse([], safe=False)

        plots = (
            Plot.objects.filter(code__istartswith=query)
            .prefetch_related(
                Prefetch(
                    'plotproperties_set',
                    queryset=PlotProperties.objects.only('name', 'value'),
                    to_attr='prefetched_properties'
                )
            )
            .order_by('code')[:25]
        )

        suggestions = [
            {
                'code': plot.code,
                'properties': [
                    {'name': prop.name, 'value': prop.value}
                    for prop in plot.prefetched_properties
                ]
            }
            for plot in plots
        ]

        return JsonResponse(suggestions, safe=False)

collector/templates/collector/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

<h1>{% trans 'Vegetation Habitat Data Collector' %}</h1>

<p>{% trans 'Demo/Prototype site for collecting observations' %}</p>

<p>{% trans 'To submit an observation, you will need to:' %}</p>

<ul>
    {% if not user.is_authenticated %}
    <li><a href="{% url 'collector:login' %}">{% trans 'login' %}</a></li>
    {% endif %}
    <li>{% trans 'allow access to your camera' %}</li>
    <li>{% trans 'allow access to your location' %}</li>
</ul>

<p>{% trans 'You\'ll be prompted for camera and location permissions when you go to add an observation' %}</p>

{% if user.is_authenticated %}
<ul>
    <li><a href="{% url 'collector:observation_wizard' %}">{% trans 'Add an Observation' %}</a></li>
    <li><a href="{% url 'collector:profile_observations' %}">{% trans 'View your observations' %}</a></li>
</ul>

<p>{% trans 'Download' %}:</p>
<ul>
    <li><a href="{% url 'collector:profile_observations_export' %}">{% trans 'Your observation data to CSV' %}</a></li>
    <li><a href="{% url 'collector:profile_observations_export_images' %}">{% trans 'Your observation images as zip package' %}</a></li>
</ul>
{% endif %}
{% endblock %}

collector/templates/collector/login.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block content %}

<h1>{% trans 'Login' %}</h1>
    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <form method="post">
    {{ form.non_field_errors }}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Username:</label>
        {{ form.username }}
        {{ form.username.errors }}
    </div>
    <div class="form-group">
        <label for="{{ form.password.id_for_label }}">Password:</label>
        {{ form.password }}
        {{ form.password.errors }}
    </div>
        <button type="submit">{% trans 'Login' %}</button>
    </form>

{% endblock %}

collector/templates/collector/map.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block extra_styles %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
{% endblock extra_styles %}

{% block extra_scripts %}
 <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>
{% endblock extra_scripts %}

{% block content %}

<h1>{% trans 'Map' %}</h1>
<div id='mapid' style="width:100%; height:700px"></div>
<script>

var photoMap = L.map('mapid').setView([62.60, 29.76], 3);

L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(photoMap);

{% for o in observations %}
        var marker = L.marker([{{ o.geo_lat }}, {{ o.geo_lng }}]).addTo(photoMap);
{% endfor %}
</script>

{% endblock %}

collector/templates/collector/observation.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}


{% block extra_scripts %}
<script defer src="{% static 'collector/camera.js' %}"></script>
<script defer src="{% static 'collector/location.js' %}"></script>
{% endblock extra_scripts %}


{% block content %}

<h1>{% trans 'Record Observation' %}</h1>

{% if form.errors %}
    <div style="color: red;">
        <h3>There were errors with your submission:</h3>
        <ul>
            {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

<form id="ObservationForm"  method="POST">
    {% csrf_token %}
    <h3>Capture Photo</h3>
    <video id="video" autoplay></video>
    <canvas id="canvas" style="display: none;"></canvas>
    <img id="photo" style="display: none;" alt="Captured Photo">
    <button id="capture" type="button">Capture</button>
    <input id="observation_image" name="observation_image">

    <h3>Location</h3>
    <label for="geo_lat">Latitude:</label>
    <input type="text" id="geo_lat" name="geo_lat" readonly>
    <br><br>
    <label for="geo_lng">Longitude:</label>
    <input type="text" id="geo_lng" name="geo_lng" readonly>

    <h3>Plot</h3>
    <label for="plot">Plot:</label>
    <input type="text" id="plot" name="plot">

    <h3></h3>
    <button type="submit" id="submitObservation">Submit Observation</button>
</form>

{% endblock %}

collector/templates/collector/observation_success.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}

<h1>{% trans 'Record Observation' %}</h1>

<h2>{% trans 'Your observation was successfully saved' %}</h2>

<h2><a href="{% url 'collector:create_observation' %}">{% trans 'Add another observation' %}</a></h2>

{% endblock %}

collector/templates/collector/user_observations.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load thumbnail %}

{% block content %}

<h1>{% trans 'Your Observations' %}</h1>

{% include 'includes/pagination.html' %}

<div class="container my-5">

        <div class="table-responsive">
            <table class="table table-bordered table-hover table-striped">
                <thead class="table-dark">
                    <tr>
                        <th>#</th>
                        <th>Date/time</th>
                        <th>Image/Location</th>
                        <th>Plot</th>
                        <th>Measurements</th>
                        <th>Species</th>
                        <th>Notes</th>
                    </tr>
                </thead>
                <tbody>
                    {% for o in observations %}
                        <tr>
                            <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                            <td>{{ o.create_date }}</td>
                            <td>
                                {% thumbnail o.image "200x200" as thumb %}
                                <img src="{{ thumb.url }}">
                                {% endthumbnail %}
                                <br/>
                                <a target="_blank"
                                   href="https://www.openstreetmap.org/?mlat={{ o.geo_lat }}&mlon={{ o.geo_lng }}">
                                    {{ o.geo_lat }},{{ o.geo_lng }}
                                </a></td>
                            <td><span class="field-title">{% trans 'Plot' %}</span>: {{ o.plot }}<br/>
                                {% if o.plot.plotproperties_set.all %}
                                <ul>
                                    {% for property in o.plot.plotproperties_set.all %}
                                      <li><span class="field-title">{{ property.name }}</span>: {{ property.value }}</li>
                                    {% endfor %}
                                  </ul>
                                {% endif %}
                                <span class="field-title">{% trans 'Block' %}</span>: {{ o.block }}<br/>
                                <span class="field-title">{% trans 'Row' %}</span>: {{ o.row }}

                                </td>
                            <td>
                                {% if o.chlorophyl %}
                                    <span class="field-title">{% trans 'Chlorophyl' %}</span>: {{ o.chlorophyl }}<br/>
                                {% endif %}
                                {% if o.fungal_disease %}
                                    <span class="field-title">{% trans 'Fungal disease' %}</span>: {{ o.fungal_disease }}<br/>
                                {% endif %}
                                {% if o.eat_marks %}
                                    <span class="field-title">{% trans 'Eat marks' %}</span>: {{ o.eat_marks }}<br/>
                                {% endif %}
                                {% if o.soil_moisture %}
                                    <span class="field-title">{% trans 'Soil moisture' %}</span>: {{ o.soil_moisture }}<br/>
                                {% endif %}
                                {% if o.electric_conductivity %}
                                    <span class="field-title">{% trans 'Electric conductivity' %}</span>: {{ o.electric_conductivity }}<br/>
                                {% endif %}
                                {% if o.temperature %}
                                    <span class="field-title">{% trans 'Temperature' %}</span>: {{ o.temperature }}<br/>
                                {% endif %}
                            </td>
                            <td>
                                <ul>
                                {% for s in o.observationspecies.all %}
                                  <li>{{ s.species.name }} - {{ s.coverage }}</li>
                                {% endfor %}
                              </ul>
                            </td>
                            <td>
                                {% if o.notes %}
                                    {{ o.notes }}
                                {% endif %}
                            </td>

                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="8" class="text-center">No data available</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% include 'includes/pagination.html' %}

{% endblock %}